// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzczifbpmrcfdxzyrygh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6Y3ppZmJwbXJjZmR4enlyeWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDc1NDYsImV4cCI6MjA2MTI4MzU0Nn0.kKzYPTsH9jeD0nkE-4XL5x2RgrIsSdzuBnGlKEe_ARY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);